package com.solvit.mobile;



import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Model notification class
 */
public class NotificationModel implements Serializable {
    private String id;
    private String completed;
    private long pc_number;
    private String role;
    private String room;
    private String building;
    private String description;
    private String user;
    private List<String> fowardTo;

    public NotificationModel() {}

    // Constructor for reading purposes
    public NotificationModel(String id, String completed, long pc_number, String role, String room, String building, String description, String user, List<String> fowardTo) {
        this.id = id;
        this.completed = completed;
        this.pc_number = pc_number;
        this.role = role;
        this.room = room;
        this.building = building;
        this.description = description;
        this.user = user;
        this.fowardTo = fowardTo;
    }

    // Constructor for writing purposes, id is autogenerated after the write
    public NotificationModel(String completed, long pc_number, String role, String room, String building, String description, String user, List<String> fowardTo) {
        this.id = id;
        this.completed = completed;
        this.pc_number = pc_number;
        this.role = role;
        this.room = room;
        this.building = building;
        this.description = description;
        this.user = user;
        this.fowardTo = fowardTo;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCompleted() {
        return completed;
    }

    public void setCompleted(String completed) {
        this.completed = completed;
    }

    public long getPc_number() {
        return pc_number;
    }

    public void setPc_number(long pc_number) {
        this.pc_number = pc_number;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getRoom() {
        return room;
    }

    public void setRoom(String room) {
        this.room = room;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public List<String> getFowardTo() {
        return fowardTo;
    }

    public void setFowardTo(List<String> fowardTo) {
        this.fowardTo = fowardTo;
    }

    public String getBuilding() {
        return building;
    }

    public void setBuilding(String building) {
        this.building = building;
    }
}
